[project]
name = "local-ai-transcription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ane-transformers>=0.1.1",
    "black>=26.1.0",
    "click>=8.3.1",
    "isort>=8.0.0",
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material>=9.7.3",
    "mkdocstrings-python>=2.0.3",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.47",
    "torch>=2.10.0",
]

[project.optional-dependencies]
ollama = [
    "ollama>=0.6.1",
]
